package com.trading.engine.engine;

import com.trading.engine.book.OrderBook;
import com.trading.engine.model.Order;
import com.trading.engine.model.Trade;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

/**
 * The core matching algorithm.
 *
 * ALGORITHM (for an incoming BUY order; SELL is symmetric):
 *   1. While the incoming order still has quantity remaining, AND
 *      the ask side is not empty, AND
 *      the best ask price <= the incoming buy price (prices "cross"):
 *        a. Look at the resting order at the best ask price (oldest first).
 *        b. Trade quantity = min(incoming remaining, resting remaining).
 *        c. Execute the trade at the RESTING order's price.
 *        d. Reduce both orders' remaining quantity by the traded amount.
 *        e. If the resting order is NOT fully filled, put it back at the
 *           FRONT of its price level (it keeps time priority) and stop
 *           the loop (incoming order must be fully filled at this point,
 *           since the resting order absorbed all remaining quantity).
 *   2. If the incoming order still has quantity left after the loop
 *      (no more crossing prices available), rest it in the book.
 *
 * This is O(log n) per matched price level (TreeMap access) plus O(1)
 * per matched order (Deque access) -- the overall cost of processing an
 * order is O(m log n) where m = number of resting orders it consumes.
 */
public class MatchingEngine {

    private final OrderBook orderBook;
    private final List<Trade> tradeLog = new ArrayList<>();
    private final AtomicLong orderIdGenerator = new AtomicLong(0);

    public MatchingEngine(String symbol) {
        this.orderBook = new OrderBook(symbol);
    }

    public OrderBook getOrderBook() {
        return orderBook;
    }

    public List<Trade> getTradeLog() {
        return tradeLog;
    }

    /** Convenience factory so callers don't have to manage order ids themselves. */
    public long nextOrderId() {
        return orderIdGenerator.incrementAndGet();
    }

    /**
     * Submits a new order to the engine. Attempts to match it immediately;
     * any unfilled remainder rests in the book.
     *
     * @return the list of trades generated by this specific submission
     *         (usually 0, 1, or a handful if it swept multiple price levels)
     */
    public List<Trade> submitOrder(Order incoming) {
        List<Trade> tradesGenerated = new ArrayList<>();
        Order.Side oppositeSide = incoming.getSide() == Order.Side.BUY ? Order.Side.SELL : Order.Side.BUY;

        while (incoming.getQuantity() > 0 && pricesStillCross(incoming, oppositeSide)) {
            Order resting = orderBook.pollBest(oppositeSide);
            if (resting == null) {
                break; // safety guard; pricesStillCross already checks emptiness
            }

            long tradeQty = Math.min(incoming.getQuantity(), resting.getQuantity());
            BigDecimal tradePrice = resting.getPrice(); // resting order's price wins

            long buyOrderId = incoming.getSide() == Order.Side.BUY ? incoming.getOrderId() : resting.getOrderId();
            long sellOrderId = incoming.getSide() == Order.Side.SELL ? incoming.getOrderId() : resting.getOrderId();

            Trade trade = new Trade(orderBook.getSymbol(), buyOrderId, sellOrderId, tradePrice, tradeQty);
            tradeLog.add(trade);
            tradesGenerated.add(trade);

            incoming.reduceQuantity(tradeQty);
            resting.reduceQuantity(tradeQty);

            if (!resting.isFullyFilled()) {
                // Resting order absorbed a partial fill and still has quantity left.
                // Put it back at the FRONT of the level -- it does not lose its
                // time-priority spot just because it was momentarily popped.
                orderBook.requeueAtFront(resting);
            }
            // If resting IS fully filled, we simply don't re-add it -- it's done.
        }

        if (incoming.getQuantity() > 0) {
            // No more crossing prices available; rest the remainder in the book.
            orderBook.addOrder(incoming);
        }

        return tradesGenerated;
    }

    /** True if the incoming order's price still crosses the best opposite price. */
    private boolean pricesStillCross(Order incoming, Order.Side oppositeSide) {
        BigDecimal bestOpposite = oppositeSide == Order.Side.SELL
                ? orderBook.bestAskPrice()
                : orderBook.bestBidPrice();

        if (bestOpposite == null) {
            return false; // nothing resting on the other side
        }

        if (incoming.getSide() == Order.Side.BUY) {
            // Buyer's price must be >= seller's ask.
            return incoming.getPrice().compareTo(bestOpposite) >= 0;
        } else {
            // Seller's price must be <= buyer's bid.
            return incoming.getPrice().compareTo(bestOpposite) <= 0;
        }
    }

    public boolean cancelOrder(long orderId) {
        return orderBook.cancelOrder(orderId);
    }
}
